import http from "node:http";
import crypto from "node:crypto";
import {spawn,execFileSync} from "node:child_process";
import {mkdtemp,rm} from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import {fileURLToPath} from "node:url";
import {WebSocketServer,WebSocket} from "ws";

const secret=process.env.SECRET_KEY,port=Number(process.env.TERMINAL_PORT||8081);
if(!secret||secret.length<32)throw Error("Set a strong SECRET_KEY");
const here=path.dirname(fileURLToPath(import.meta.url)),project=path.resolve(here,".."),teamRe=/^[1-9][0-9]{0,5}$/;
function ticket(token){const [a,b,c]=String(token||"").split("."),sig=crypto.createHmac("sha256",secret).update(`${a}.${b}`).digest(),got=Buffer.from(c||"","base64url");if(!a||!b||got.length!==sig.length||!crypto.timingSafeEqual(got,sig))throw Error("invalid ticket");const x=JSON.parse(Buffer.from(b,"base64url"));if(x.scope!=="terminal"||!teamRe.test(String(x.team))||x.exp<Date.now()/1000)throw Error("expired ticket");return x}
function run(args,options={}){return execFileSync("podman",args,{encoding:"utf8",timeout:60000,maxBuffer:8*1024*1024,...options})}
const name=id=>{if(!teamRe.test(String(id)))throw Error("invalid team");return `escape-team-${id}`};
async function provision(id,seed){const n=name(id);if(!/^[a-f0-9]{64}$/.test(seed))throw Error("invalid seed");try{run(["rm","-f",n],{stdio:"ignore"})}catch{}
 run(["run","-d","--name",n,"--network","none","--read-only","--user","player","--memory","256m","--cpus","0.5","--pids-limit","128","--cap-drop","all","--security-opt","no-new-privileges","--tmpfs","/tmp:rw,noexec,nosuid,size=32m","--tmpfs","/escape:rw,nosuid,nodev,size=64m,uid=100,gid=101,mode=0755","localhost/escape-player:locked","sleep","2147483"]);
 const tmp=await mkdtemp(path.join(os.tmpdir(),"escape-team-"));try{const root=path.join(tmp,"escape"),g=spawn("python3",[path.join(project,"challenges/generate_instance.py"),seed,"--root",root],{stdio:"inherit"});await new Promise((ok,no)=>{g.on("error",no);g.on("close",c=>c===0?ok():no(Error(`generator exit ${c}`)))});const data=execFileSync("tar",["--owner=100","--group=101","--numeric-owner","-C",root,"-cf","-","."],{maxBuffer:8*1024*1024});run(["exec","-i","--user","player",n,"tar","-C","/escape","-xf","-"],{input:data,stdio:["pipe","ignore","pipe"]});run(["exec","--user","player",n,"chmod","200","/escape/room4/password.txt"])}catch(e){try{run(["rm","-f",n],{stdio:"ignore"})}catch{}throw e}finally{await rm(tmp,{recursive:true,force:true})}return{team_id:Number(id),status:"ready"}}
const server=http.createServer(async(req,res)=>{if(req.url==="/health"){res.writeHead(200,{"content-type":"application/json"});return res.end('{"status":"ok","runtime":"rootless-podman"}')}const m=req.url?.match(/^\/internal\/teams\/([1-9][0-9]{0,5})\/provision$/);if(req.method!=="POST"||!m){res.writeHead(404);return res.end()}const k=Buffer.from(String(req.headers["x-worker-key"]||"")),s=Buffer.from(secret);if(k.length!==s.length||!crypto.timingSafeEqual(k,s)){res.writeHead(403);return res.end()}let raw="";for await(const chunk of req)raw+=chunk;if(raw.length>4096){res.writeHead(413);return res.end()}try{const result=await provision(m[1],JSON.parse(raw).seed);res.writeHead(200,{"content-type":"application/json"});res.end(JSON.stringify(result))}catch(e){console.error("provision failed",e.message);res.writeHead(503);res.end('{"detail":"Provisioning failed"}')}});
const wss=new WebSocketServer({noServer:true,maxPayload:4096});server.on("upgrade",(req,socket,head)=>{try{const u=new URL(req.url,"http://localhost");if(u.pathname!=="/ws/terminal")throw Error();ticket(u.searchParams.get("ticket"));wss.handleUpgrade(req,socket,head,ws=>wss.emit("connection",ws,req))}catch{socket.write("HTTP/1.1 401 Unauthorized\r\n\r\n");socket.destroy()}});
wss.on("connection",(ws,req)=>{let claims;try{claims=ticket(new URL(req.url,"http://localhost").searchParams.get("ticket"))}catch{ws.close(4401);return}const child=spawn("podman",["exec","-i","-t","--user","player","--workdir","/home/player",name(claims.team),"/bin/bash","--noprofile","--norc"],{stdio:["pipe","pipe","pipe"]});child.stdout.on("data",d=>ws.readyState===WebSocket.OPEN&&ws.send(d));child.stderr.on("data",d=>ws.readyState===WebSocket.OPEN&&ws.send(d));child.on("error",()=>ws.close(1011,"shell unavailable"));child.on("close",()=>ws.readyState===WebSocket.OPEN&&ws.close(1011,"shell ended"));ws.on("message",d=>child.stdin.writable&&child.stdin.write(d));ws.on("close",()=>child.kill("SIGTERM"))});
server.listen(port,"0.0.0.0",()=>console.log(`Rootless terminal worker listening on ${port}`));
